In [1]:
#import libreary 
import pandas as pd

In [2]:
#empty df 
df=pd.Dataframe

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [3]:
df=pd.Dataframe

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [4]:
df=pd.Dataframe()

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [5]:
df=pd.Dataframe()
df

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [6]:
import pandas as pd

In [7]:
df=pd.Dataframe()
df

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [8]:
df.info()

NameError: name 'df' is not defined

In [9]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [10]:
pd.info()

AttributeError: module 'pandas' has no attribute 'info'

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame

In [12]:
city=["dhaka","sylhet","barisal","new york"]

In [13]:
df=pd.DataFrame(city)

In [14]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [15]:
df=pd.DataFrame(city)
df

          0
0     dhaka
1    sylhet
2   barisal
3  new york

In [16]:
df=pd.DataFrame('city' ,columns=["city of bd"] ,index=["city1,city2,city3,city4"])
df

                        city of bd
city1,city2,city3,city4       city

In [17]:
f=pd.DataFrame(city ,columns=["city of bd"] ,index=["city1,city2,city3,city4"])
df

ValueError: Shape of passed values is (4, 1), indices imply (1, 1)

In [18]:
df=pd.DataFrame('city' ,columns=["city of bd"] ,index=["city1,city2,city3,city4"])
df

                        city of bd
city1,city2,city3,city4       city

In [19]:
df=pd.Dataframe(city)
df

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [20]:
df=pd.DataFrame(city)
df

          0
0     dhaka
1    sylhet
2   barisal
3  new york

In [21]:
df

          0
0     dhaka
1    sylhet
2   barisal
3  new york

In [22]:
df=pd.DataFrame(city,columns="city of bd")
df

TypeError: Index(...) must be called with a collection of some kind, 'city of bd' was passed

In [23]:
df=pd.DataFrame(city,columns=["city of bd"])
df

  city of bd
0      dhaka
1     sylhet
2    barisal
3   new york

In [24]:
df=pd.DataFrame(city,columns="city of bd",index=["c1,c2,c2,c4"])
df

TypeError: Index(...) must be called with a collection of some kind, 'city of bd' was passed

In [25]:
df=pd.DataFrame(city,columns="city of bd",index=["c1","c2","c2","c4"])
df

TypeError: Index(...) must be called with a collection of some kind, 'city of bd' was passed

In [26]:
df=pd.DataFrame(city,columns="city of bd", index=["c1","c2","c2","c4"])
dfdf=pd.DataFrame(city,columns="city of bd", index=["c1","c2","c2","c4"])
df

TypeError: Index(...) must be called with a collection of some kind, 'city of bd' was passed

In [27]:
df=pd.DataFrame(city,columns="city of bd", index=["c1","c2","c2"])
df

TypeError: Index(...) must be called with a collection of some kind, 'city of bd' was passed

In [28]:
df=pd.DataFrame(city,columns="city of bd")
df

TypeError: Index(...) must be called with a collection of some kind, 'city of bd' was passed

In [29]:
df=pd.DataFrame(city, index=['c1','c2','c3','c4'])
df

           0
c1     dhaka
c2    sylhet
c3   barisal
c4  new york

In [30]:
df=pd.DataFrame(city,columns=["city of bd"])
df

  city of bd
0      dhaka
1     sylhet
2    barisal
3   new york

In [31]:
df=pd.DataFrame(city,columns=["city of bdd"] , index=['c1','c2','c3','c4'])
df

   city of bdd
c1       dhaka
c2      sylhet
c3     barisal
c4    new york

In [32]:
city2=["rajshahi","khulna","mirpur","subidbazar"]
df2=pd.DataFrame(zip(city,city2), columns = ["marge city"] , index=['c1','c2','c3','c4'])
df2

ValueError: 1 columns passed, passed data had 2 columns

In [33]:
city2=["rajshahi","khulna","mirpur","subidbazar"]
df2=pd.DataFrame(zip(city,city2), columns = ['city1','city2'] , index=['c1','c2','c3','c4'])
df2

       city1       city2
c1     dhaka    rajshahi
c2    sylhet      khulna
c3   barisal      mirpur
c4  new york  subidbazar

In [34]:
df2.shape

(4, 2)

In [35]:
city3=[["mirpur,kuril"] , ["gulsan","demra"]]

In [36]:
df3=pd.DataFrame(city3)
df3

              0      1
0  mirpur,kuril   None
1        gulsan  demra

In [37]:
dict1 = {
    
     'city': city1,
     'city2' : city2
    
}

NameError: name 'city1' is not defined

In [38]:
dict1 = {
    
     'city': city,
     'city2' : city2
    
}

In [39]:
dict1

{'city': ['dhaka', 'sylhet', 'barisal', 'new york'],
 'city2': ['rajshahi', 'khulna', 'mirpur', 'subidbazar']}

In [40]:
dfd= pd.DataFrame(dict1)
dfd

       city       city2
0     dhaka    rajshahi
1    sylhet      khulna
2   barisal      mirpur
3  new york  subidbazar

In [41]:
dfd.shape

(4, 2)

In [42]:
df=pd.read_csv('Screen Time Data')

FileNotFoundError: [Errno 2] No such file or directory: 'Screen Time Data'

In [43]:
df

   city of bdd
c1       dhaka
c2      sylhet
c3     barisal
c4    new york

In [44]:
df=pd.read_csv('Screen Time Data')

FileNotFoundError: [Errno 2] No such file or directory: 'Screen Time Data'

In [45]:
df=pd.read_csv('Screen Time Data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Screen Time Data.csv'

In [46]:
df=pd.read_csv('Screen Time Data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Screen Time Data.csv'

In [47]:
df=pd.read_csv('F:\excel\Screen Time Data.csv')

In [48]:
df

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0
5,5,04/22/19,Monday,189,68,0,9,3,4,0,0,0
6,6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0
7,7,04/24/19,Wednesday,135,98,3,33,16,0,0,0,0
8,8,04/25/19,Thursday,52,25,7,3,16,0,0,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
10,10,04/27/19,Saturday,116,75,10,20,5,0,0,0,0
11,11,04/28/19,Sunday,85,42,22,4,2,0,0,0,0
12,12,04/29/19,Monday,109,46,8,13,9,15,1,0,1
13,13,04/30/19,Tuesday,79,40,2,9,12,0,0,0,1
14,14,05/01/19,Wednesday,127,90,0,10,7,0,0,0,1
15,15,05/02/19,Thursday,170,60,3,2,11,0,0,0,1
16,16,05/03/19,Friday,91,64,2,18,5,1,1,2,1
17,17,05/04/19,Saturday,58,34,4,5,3,0,1,0,1
18,18,05/05/19,Sunday,133,109,5,1,3,0,0,0,1
19,19,05/06/19,Monday,144,81,4,5,3,0,0,0,1
20,20,05/07/19,Tuesday,110,70,5,6,15,0,9,0,1
21,21,05/08/19,Wednesday,122,53,25,26,15,0,0,0,1
22,22,05/09/19,Thursday,96,42,15,16,19,0,0,0,1
23,23,05/10/19,Friday,161,93,13,17,16,1,0,0,1
24,24,05/11/19,Saturday,58,49,1,2,2,0,0,2,1
25,25,05/12/19,Sunday,52,28,1,1,6,0,0,1,1
26,26,05/13/19,Monday,61,37,1,0,4,0,0,0,1
27,27,05/14/19,Tuesday,88,41,2,7,15,0,0,0,1

In [49]:
df.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [50]:
df

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0
5,5,04/22/19,Monday,189,68,0,9,3,4,0,0,0
6,6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0
7,7,04/24/19,Wednesday,135,98,3,33,16,0,0,0,0
8,8,04/25/19,Thursday,52,25,7,3,16,0,0,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
10,10,04/27/19,Saturday,116,75,10,20,5,0,0,0,0
11,11,04/28/19,Sunday,85,42,22,4,2,0,0,0,0
12,12,04/29/19,Monday,109,46,8,13,9,15,1,0,1
13,13,04/30/19,Tuesday,79,40,2,9,12,0,0,0,1
14,14,05/01/19,Wednesday,127,90,0,10,7,0,0,0,1
15,15,05/02/19,Thursday,170,60,3,2,11,0,0,0,1
16,16,05/03/19,Friday,91,64,2,18,5,1,1,2,1
17,17,05/04/19,Saturday,58,34,4,5,3,0,1,0,1
18,18,05/05/19,Sunday,133,109,5,1,3,0,0,0,1
19,19,05/06/19,Monday,144,81,4,5,3,0,0,0,1
20,20,05/07/19,Tuesday,110,70,5,6,15,0,9,0,1
21,21,05/08/19,Wednesday,122,53,25,26,15,0,0,0,1
22,22,05/09/19,Thursday,96,42,15,16,19,0,0,0,1
23,23,05/10/19,Friday,161,93,13,17,16,1,0,0,1
24,24,05/11/19,Saturday,58,49,1,2,2,0,0,2,1
25,25,05/12/19,Sunday,52,28,1,1,6,0,0,1,1
26,26,05/13/19,Monday,61,37,1,0,4,0,0,0,1
27,27,05/14/19,Tuesday,88,41,2,7,15,0,0,0,1

In [51]:
df.values

array([[0, '04/17/19', 'Wednesday', 187, 89, 17, 41, 22, 0, 0, 0, 0],
       [1, '04/18/19', 'Thursday', 123, 78, 17, 8, 9, 0, 0, 0, 0],
       [2, '04/19/19', 'Friday', 112, 52, 40, 8, 4, 0, 3, 0, 0],
       [3, '04/20/19', 'Saturday', 101, 69, 9, 38, 2, 0, 3, 0, 0],
       [4, '04/21/19', 'Sunday', 56, 35, 2, 43, 3, 0, 1, 1, 0],
       [5, '04/22/19', 'Monday', 189, 68, 0, 9, 3, 4, 0, 0, 0],
       [6, '04/23/19', 'Tuesday', 158, 56, 18, 41, 12, 15, 0, 0, 0],
       [7, '04/24/19', 'Wednesday', 135, 98, 3, 33, 16, 0, 0, 0, 0],
       [8, '04/25/19', 'Thursday', 52, 25, 7, 3, 16, 0, 0, 0, 0],
       [9, '04/26/19', 'Friday', 198, 76, 8, 29, 15, 0, 32, 0, 0],
       [10, '04/27/19', 'Saturday', 116, 75, 10, 20, 5, 0, 0, 0, 0],
       [11, '04/28/19', 'Sunday', 85, 42, 22, 4, 2, 0, 0, 0, 0],
       [12, '04/29/19', 'Monday', 109, 46, 8, 13, 9, 15, 1, 0, 1],
       [13, '04/30/19', 'Tuesday', 79, 40, 2, 9, 12, 0, 0, 0, 1],
       [14, '05/01/19', 'Wednesday', 127, 90, 0, 10, 7, 0, 0, 0, 1],
       [15, '05/02/19', 'Thursday', 170, 60, 3, 2, 11, 0, 0, 0, 1],
       [16, '05/03/19', 'Friday', 91, 64, 2, 18, 5, 1, 1, 2, 1],
       [17, '05/04/19', 'Saturday', 58, 34, 4, 5, 3, 0, 1, 0, 1],
       [18, '05/05/19', 'Sunday', 133, 109, 5, 1, 3, 0, 0, 0, 1],
       [19, '05/06/19', 'Monday', 144, 81, 4, 5, 3, 0, 0, 0, 1],
       [20, '05/07/19', 'Tuesday', 110, 70, 5, 6, 15, 0, 9, 0, 1],
       [21, '05/08/19', 'Wednesday', 122, 53, 25, 26, 15, 0, 0, 0, 1],
       [22, '05/09/19', 'Thursday', 96, 42, 15, 16, 19, 0, 0, 0, 1],
       [23, '05/10/19', 'Friday', 161, 93, 13, 17, 16, 1, 0, 0, 1],
       [24, '05/11/19', 'Saturday', 58, 49, 1, 2, 2, 0, 0, 2, 1],
       [25, '05/12/19', 'Sunday', 52, 28, 1, 1, 6, 0, 0, 1, 1],
       [26, '05/13/19', 'Monday', 61, 37, 1, 0, 4, 0, 0, 0, 1],
       [27, '05/14/19', 'Tuesday', 88, 41, 2, 7, 15, 0, 0, 0, 1]],
      dtype=object)

In [52]:
df.corr()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9956\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,index,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
index,1.000000,-0.344952,-0.218093,-0.360073,-0.537331,0.012553,-0.178863,-0.113858,0.221908,0.857690
Total Screen Time,-0.344952,1.000000,0.710864,0.185685,0.333433,0.344195,0.201360,0.343897,-0.409306,-0.258123
Social Networking,-0.218093,0.710864,1.000000,0.004461,0.234066,0.124539,-0.092968,0.132916,-0.214764,-0.110716
Reading and Reference,-0.360073,0.185685,0.004461,1.000000,0.204553,0.162942,0.091587,0.012539,-0.302112,-0.381038
Other,-0.537331,0.333433,0.234066,0.204553,1.000000,0.307073,0.236715,0.192795,-0.023360,-0.529736
Productivity,0.012553,0.344195,0.124539,0.162942,0.307073,1.000000,0.032934,0.186832,-0.336026,-0.001722
Health and Fitness,-0.178863,0.201360,-0.092968,0.091587,0.236715,0.032934,1.000000,-0.075065,-0.094262,-0.066414
Entertainment,-0.113858,0.343897,0.132916,0.012539,0.192795,0.186832,-0.075065,1.000000,-0.083521,-0.203577
Creativity,0.221908,-0.409306,-0.214764,-0.302112,-0.023360,-0.336026,-0.094262,-0.083521,1.000000,0.203286
Yoga,0.857690,-0.258123,-0.110716,-0.381038,-0.529736,-0.001722,-0.066414,-0.203577,0.203286,1.000000